### ISSUE TITLE
Default resource needs to be retrieved from the environment

### ISSUE THREAD

**Issue by tempoz** [irods/irods_api_plugin_multipart#3]
Right now it is hard-coded to `demoResc`, requiring users who do not have that resource to specify the resource they want on the command line, otherwise failing in a way that is not obvious without access to the server log.

**Comment by trel** [comment]
Archiving this repository.

The new multipart mechanism was shipped in iRODS 4.2.9:
https://github.com/irods/irods/issues/4336
