### ISSUE TITLE
Get hangs when the destination file already exists

### ISSUE THREAD

**Issue by tempoz** [irods/irods_api_plugin_multipart#4]
Instead, return an error message and exit.

**Comment by tempoz** [comment]
Client interaction function was not being communicated with and thus hung, and the client cannot exit until the client interaction has exited. Have to end communication with the client interaction first.

**Comment by trel** [comment]
Archiving this repository.

The new multipart mechanism was shipped in iRODS 4.2.9:
https://github.com/irods/irods/issues/4336
